name = "coyote"
description = "Coyote \u2014 native Ada LLM coding agent for Acme"
version = "0.1.0-dev"

authors = ["Garret Noble"]
maintainers = ["Garret Noble <garretnoble@gmail.com>"]
maintainers-logins = ["gtnoble"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

[[depends-on]]
gnatcoll = "^25.0.0"

